name: Configure VM for codemeta-ro-crate-vm
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
jobs:
  setup-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Script Repository
      uses: actions/checkout@v4
    - name: 'Clone Target Repository: codemeta-ro-crate-vm'
      run: git clone https://github.com/firmao/codemeta-ro-crate-vm.git target_repo
    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-pip
    - name: Configure Environment
      working-directory: ./target_repo
      run: 'if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        if [ -f setup.sh ]; then chmod +x setup.sh && ./setup.sh; fi'
    - name: Run Software
      working-directory: ./target_repo
      run: '# Add your execution command here, e.g., python main.py'
